server/button.js, server/params.js, server/server.js, test/server/mock.js, test/server/render.button.test.js
* receives callgqlforfundingeligibility handler
* retrieves funding eligibility on its own and not depend on req.query
=> call gql function passed down for funding eligibility

src/api/index.js, src/api/order.js, src/api/subscription.js, src/button/button.js, src/button/props/createOrder.js, src/button/props/createSubscription.js, src/button/props/index.js, src/button/props/onApprove.js, src/button/props/props.js, src/button/props/types.js, src/config.js, src/constants.js, src/payment-flows/card-fields.js, src/payment-flows/checkout.js, test/client/actions.js, test/client/happy.js, test/client/mocks.js
Add  support to create, revise, get and activate subscriptions from smart buttons
=> feat(subscriptions) Add Subscriptions to Smart Buttons

server/devServer.js, src/wallet/components/credit/index.jsx, src/wallet/components/page/index.jsx, src/wallet/components/wallet/index.jsx, src/wallet/components/walletItem/index.jsx, src/wallet/types.js, src/wallet/util.js
- added a component for paypal credit to insert their messaging
- removed a bunch of state maintaining code and brought it into util.js
- fixed some spacing errors from the last linter commit
=> Wallet Refactoring

src/button/button.js, src/constants.js, src/lib/comms.js, src/lib/index.js, src/types.js
=> trigger validation for smartfields

src/button/button.js, src/button/pay.js, src/types.js, test/client/funding.js, test/client/index.js, test/client/mocks.js, test/client/smart-fields.js
adds the confirm call when it is for a smartfield
=> add confirm call for alt payments

package.json, server/components/buttons/params.js, server/service/fundingEligibility.js, src/api/order.js, src/button/props.js, src/constants.js, src/payment-flows/types.js, src/payment-flows/vault-capture.js, test/client/vault.js
Initiating installments flow based on eligibility and button flag for vaulted flow.
=> Vaulted card installments implementation

src/payment-flows/native.js
Opens connection to Firebase to allow time for messages to be sent to Android sooner when error conditions exist.
=> Update Android Firebase Connection

src/api/eligibility.js, src/payment-flows/checkout.js, src/payment-flows/native.js
Working on adding support for the enableFunding query param
=> Pass 'enableFunding' option to graphql mobileSDKEligibility query

src/constants.js, src/payment-flows/native.js, test/client/mocks.js, test/client/native.js
- Added listeners for on_fallback message coming from native Android SDK https://engineering.paypalcorp.com/jira/browse/DTCHKINT-424
=> DTCHKINT-424 Design Implement Fallback Android

src/constants.js
=> (ramp) Ramping upgradeLSAT to 10%

src/constants.js
Buying time for `xobuyernodeserv`
=> Revert "(ramp) Ramping upgradeLSAT to 10%"

src/api/eligibility.js, src/payment-flows/native.js
Reverts paypal/paypal-smart-payment-buttons#117
=> Revert "Add buyerLanguage"

src/native/popup/popup.js, src/payment-flows/native.js
- Allows us to distinguish who is calling closePopup to discern native specific drop-offs in top of funnel
- Allows us to discern no opener logs based on hash in kibana.
=> Update native logging

src/payment-flows/native.js
- Adds button session id to send message for closeNative
=> DTCHKINT-565 web add contxt id and button session id to rtdb request and response messages

src/api/order.js, src/button/button.js, src/button/pay.js, src/button/props.js, src/constants.js, src/props/confirmOrder.js, src/props/index.js, src/types.js, test/client/auth.js, test/client/mocks.js, test/client/smart-fields.js, test/declarations.js
Retrieves the payload from sessionStorage and makes confirm payment call.
=> Add confirm api call

src/native/popup/popup.js
Added logs to determine remaining SFVC drop-offs.
=> Add popup logs

src/api/socket.js, src/payment-flows/native.js
Passed in data for socket.on callbacks
=> Add Message Data For Firebase Callbacks

src/api/order.js
Logging was recently added for pay-with-nonce path but is not actually needed
=> Remove honey logging

src/api/order.js, src/button/pay.js, src/button/props.js
The change supports CCO requirements for pay with nonce flow
=> Add data-user-experience-flow

src/api/api.js
throws the error details message if there is an error on an api call.
=> format error details message

src/button/exports.js
Add existing `commit` prop to exports
=> Export commit

src/native/popup/popup.js, src/payment-flows/native.js, test/client/native.js
Ensures that the popup window is not closed until `onApprove` is called.  When the popup window closes prior to the `onApprove` message being received from native, the wrong tab is opened that is not the merchants page.
=> Fix firebase issue

webpack.config.js
Reverts paypal/paypal-smart-payment-buttons#153
=> Revert "Add 'web: false' to webpack config"

src/api/api.js, src/api/order.js, src/constants.js, src/props/onApprove.js
Attempt to fix onApprove capturing and instrument fallback scenario for insights into failure.
=> Fallback to smartAPI

server/components/qrcode/constants.js, server/components/qrcode/middleware.js
Moving VENMO_BLUE constant into server folder.
=> QR Code Fix

server/components/buttons/script.js, server/components/menu/script.js, server/components/native/script.js, server/components/qrcode/script.js, server/watchers.js
This PR adds logging so we know when the `latest` dist tag has been downloaded with grabthar `poll()`.
=> Log when the latest dist tag has been downloaded

src/native/popup/popup.js
https://engineering.paypalcorp.com/jira/browse/DTCHKINT-789
=> Use Replace

src/payment-flows/checkout.js, src/payment-flows/native/native.js, test/client/happy.js, test/client/native.js
https://engineering.paypalcorp.com/jira/browse/DTCHKINT-867
=> Prevent onCancel if onClick Fails

src/payment-flows/applepay/applepay.js
https://engineering.paypalcorp.com/jira/browse/DTAPMWALL-132
=> Fix ApplePay completePayment

server/service/wallet.js, src/types.js
- Similar to the "Pay Now" button for returning Pay Later users, we need to create a button for returning Venmo Pay buyers that have Venmo branding and has the buyer's Venmo username in there.
- [This PR](https://github.com/paypal/paypal-checkout-components/pull/1647) in `paypal-checkout-components` contains the visual changes required in order to show the required label
- And [this one](https://github.paypal.com/Checkout-R/xobuyernodeserv/pull/2152) in `xobuyernodeserv` retrieves such data from the API
- Till now I couldn't render the right button using the demo, however,  I got the graphQL query built, which I leave below
```graphql
query GetSmartWallet(
$clientID: String!
$merchantID: [String!]
$currency: String
$amount: String
$userIDToken: String
$userRefreshToken: String …
```
=> venmo wallet support added

src/api/order.js, src/button/pay.js, src/button/validation.js, src/constants.js
Added the check to restrict all items in the order to be of `DONATION` category when the `donate` label is used for SPB.
=> feat: Add eligibility check for donate SPB

src/payment-flows/native/qrcode.js
Removing `getNativeEligibility` call for Venmo Desktop.
=> fix(qrcode): Removing mobile eligibility call from desktop

src/payment-flows/native/qrcode.js
Reverts paypal/paypal-smart-payment-buttons#213
=> Revert "fix(qrcode): Removing mobile eligibility call from desktop"

src/payment-flows/native/qrcode.js
Venmo Desktop requires part of native eligibility check except for User Agent checks w.r.t. being on a mobile device.
=> Fix Venmo Desktop Eligibility

server/components/buttons/middleware.js, server/components/buttons/params.js, server/service/personalization.jsx
This PR is about the Upfront Presentment project and adds a new queryParam so we can show the tagline for multiple buttons using Personalization Studio.
https://engineering.paypalcorp.com/jira/browse/DTNAVYA-1153
=> feat(DTNAVYA-1153): Add logic to show tagline for multiple buttons

src/payment-flows/native/popup.js, src/payment-flows/native/qrcode.js
Reverts paypal/paypal-smart-payment-buttons#216
@mnicpt Let me know I implemented this in the wrong place.  This should be implemented in the `setupLogger` function.  I am reverted this PR and creating another one.
=> Revert "chore(logging): Add funding source to app switch"

src/button/pay.js, src/props/createOrder.js
🚨 Please review the [guidelines for a good PR Description](https://www.pullrequest.com/blog/writing-a-great-pull-request-description/)
High level description of the change being made. Include any diagrams you have available.
❤️  Thank you!
=> Fix Tracking Builder for Receiver Order

package.json, src/button/logger.js, src/button/pay.js, src/native/popup/popup.js, src/payment-flows/native/native.js, src/payment-flows/native/popup.js
🚨 Please review the [guidelines for a good PR Description](https://www.pullrequest.com/blog/writing-a-great-pull-request-description/)
High level description of the change being made. Include any diagrams you have available.
❤️  Thank you!
=> Fix Native Logging

src/payment-flows/native/qrcode.js, src/qrcode/qrcard.jsx, src/types.js
=> Fix Venmo Desktop Escape Path

src/button/logger.js, src/constants.js
Adds required time key for Amplitude logs for fine-grained timestamps.
https://venmoinc.atlassian.net/browse/VMORECOMBO-310
=> Add Time Key for Amplitude

src/payment-flows/native/eligibility.js, test/client/native.js
- Fix native tests
- Move opt in below opt out for easier testing
=> Fix tests for native

src/api/fraudnet.js, src/api/order.js
Reverts paypal/paypal-smart-payment-buttons#300
=> Revert "feat(fraudnet): resend fraudnet data for one click checkout"

server/service/personalization.jsx
- Changes name of field being queried to match changes
- https://engineering.paypalcorp.com/jira/browse/DTUPSTREAM-262
❤️  Thank you!
=> Match GQL schema change

server/components/buttons/middleware.js, server/components/buttons/params.js, src/button/props.js, src/card/props.js, src/payment-flows/card-form.js, src/props/props.js
Provides custom styling for Inline XO merchants.
**Conditions to be met for the inline flag to be set:**
1. Merchant's clientID is whitelisted. 
2. Custom styling is provided.
3. FUNDING.CARD is eligible
=> Inline XO Styling

server/components/qrcode/constants.js, server/components/qrcode/middleware.js, server/components/qrcode/params.js, src/constants.js, src/qrcode/components.jsx, src/qrcode/qrcard.jsx
This reverts commit 2e2fe93e80ef4e4f811f9ffe12dc697b41aad1f3.
=> Revert "Feature/vqrc redesign (#333)"

server/.eslintrc.js, server/components/buttons/instrumentation.js, server/components/buttons/middleware.js, server/types.js, test/server/mock.js, test/server/render.button.test.js
Pass the previous Draft PR from @wsbrunson  here: https://github.com/paypal/paypal-smart-payment-buttons/pull/396
❤️  Thank you!
=> root txn data for Cal for spb

src/button/pay.js, src/payment-flows/card-form.js, src/payment-flows/checkout.js, src/props/onShippingAddressChange.js, src/props/onShippingOptionsChange.js, test/client/inlinexo.js
Updates logging requirements for Inline XO.
=> Inline XO: Update logging

test/client/validation.js
@borodovisin was looking into this test before he left but couldn't find a root cause. It's intermittently failing on other PRs and blocking us from publishing. Let's turn it off until we can figure out why it's flakey.
=> quarantine flakey test

src/api/order.js, src/payment-flows/checkout.js, src/props/onShippingAddressChange.js, src/props/onShippingOptionsChange.js, src/props/utils.js, test/client/inlinexo.js, test/client/mocks.js, test/client/onShippingAddressChange.js, test/client/onShippingOptionsChange.js, test/client/props-utils.js
Updates new shipping callbacks to determine patch op.
=> fix: Update shipping callbacks

test/client/index.js, test/client/nativePopup.js
=> Fix failing native tests

src/button/logger.js, src/button/pay.js, src/payment-flows/checkout.js, src/props/createOrder.js, src/props/onApprove.js, src/props/onCancel.js, src/props/onComplete.js, src/props/onShippingAddressChange.js, src/props/onShippingChange.js, src/props/onShippingOptionsChange.js, test/client/onShippingAddressChange.js, test/client/onShippingOptionsChange.js
Adds `event_name` to FPTI logs for Amplitude in Checkout Dev project.
This is required for visibility of the logs.
=> Add event_name to logs

src/middleware/vault-setup.js, test/client/vault.js
Currently with a client-token integration, we automatically enable vaulting for vaultable instruments. This change prevents that from happening if an id-token was also passed in to the sdk.
We want to start promoting and transitioning vaulting functionality to use the id-token integration path, but the hosted-fields integration still requires a client token until it is replaced. This PR allows us to support both id-token and client-token data attributes so that hosted fields continues to work as expected, while SPB will use the id-token approach.
- Integrate using a vaulting test scenario with Hosted Fields and SPB
- When initializing, apply both the client-token and id-token
- Upon clicking the PayPal button, you should not see the `enableVault` mutation get called
N/A
N/A
❤️  Thank you!
=> Support both client token and id-token in script tag

src/api/order.test.js, src/button/props.test.js
ppof unit tests for nate's pr (we paired on this)
=> Add unit tests

README.md
=> chore: update github actions badge url

src/card/docs/README.md, src/card/docs/Vaulting/README.md
Initial docs for Vault with Purchase functionality with new HCF. General flow outlined, details for specific card types coming with those specific tickets. No functionality changes required for Vault with Purchase for HCF.
[DTNOR-551](https://paypal.atlassian.net/browse/DTNOR-551)
@paypal/js-sdk-maintainers 
❤️  Thank you!
=> HCF Vault with Purchase documentation

src/payment-flows/native/eligibility.js
We added a [fix for Venmo in stage](#546) last week, but that had some negative effects on the PayPal button. So we want to keep the environment check in, but don't check the environment for Venmo.
https://paypal.slack.com/archives/CLKPA7686/p1677501252842249
- In stage
- **Click the paypal button**
- Before this fix: its broken & loads infinitely 
- After this fix: it should work as anticipated
@elizabethmv @gregjopa 
❤️  Thank you!
=> Fix for Native Eligibility in Stage

src/card/logger.test.js, test/declarations.js
Adding tests for logger to bring the test coverage stable
❤️  Thank you!
=> Card logger tests

src/api/order.js, src/button/pay.js
Some tweaks to the logging added with #600.
* Removed ecToken properties, as our logger already adds these.
* Moved `resolved` log to capture missing payment flows
* Moved `redirect` log from `finally` to `then` to avoid logging on failed calls
* Added logs for the non-blocking use-case as well
❤️  Thank you!
=> Ubcc logging

src/constants.js, src/lib/register-service-worker.test.js
CDN scope for Service worker was changed and it needs to be mirrored here in the service worker registration.
https://engineering.paypalcorp.com/confluence/display/BEAM/App+Shell+Testing
❤️  Thank you!
=> App Shell: Service Worker Constant needs to match CDN

.github/workflows/main.yml, .gitignore, package.json, vite.config.js
This PR adds `vitest --coverage` output to `codecov`'s coverage stats.
There have been a [few](https://github.com/paypal/paypal-smart-payment-buttons/pull/661/files#diff-6ff70a9568d157b130cfcc04c11465fa803312d358b057769e5a9f8df8505397R126-R127) [recent](https://github.com/paypal/paypal-smart-payment-buttons/pull/646/files#diff-7103fb2bee9927f927770d4e6c29f8677fbf56518eb181d534305144f0d0c62dR388-R389) [PRs](https://github.com/paypal/paypal-smart-payment-buttons/pull/656/files#diff-6ff70a9568d157b130cfcc04c11465fa803312d358b057769e5a9f8df8505397R172-R173) where codecov will comment on the PR saying the added line is missing coverage. This is true insofar as the lines were not tested with `karma`, but _were_ tested with `vitest`. This change will include the code coverage report generated by …
=> Add vitest coverage to codecov

src/api/payment.js
Reverts paypal/paypal-smart-payment-buttons#688
Has dependency on xobuyer release
=> Revert "feat: send product flow to approve payment mutation"

src/button/logger.js
* Downgraded the `server_render_version_mismatch` event to a more appropriate log level.
❤️ Thank you!
=> chore: downgrade SSR version mismatch log
