src/api/auth.js
src/api/subscription.js
src/button/props.js
src/props/createSubscription.js
test/client/happy.js

Support 3rd party token for subscription
Recreate the access token with 3rd party credentials with target as merchantID if merchantID is passed.
Create the token on button render when createSubscription prop is passed to Button so that memoization can store the access token for use while clicking the button.
On Button Click call create Token method and let memoized value to be used if available.

Feat - Support 3rd party use case for subscriptions

---

src/constants.js
src/payment-flows/native.js

Instrumentation for the following usecases:
- When setting the props, (we need to know if all of them will be making it to firebase `process_set_props_attempt`)
- When attempting the app-switch, (we need to know what will be making it in the url to native `app_switch_attempted`)
- When coming back from native, (we need a log that confirms that the popup was closed `process_popup_closed`)

Native instrumentation

---

src/button/props.js
src/constants.js
src/payment-flows/card-fields.js
src/payment-flows/checkout.js
src/props/index.js
src/props/onApprove.js
src/props/onAuth.js
src/wallet/props.js
test/client/auth.js
test/client/mocks.js

This feature is meant to deprecate clientside API calls to smartcomponentnodeweb with the intention of fulfilling the transaction.

Introducing upgradeLSAT calls on onAuth callback

---

src/payment-flows/checkout.js

This PR passes in a reference to the `restart` function to fix memoizing the `onApprove` callback.
We have been troubleshooting why memoize isn't working with the `onApprove` callback. We are thinking it's related to the `restart` function getting declared on every `onApprove` call which makes it's the arguments unique and breaks the memoization. 
We haven't been able to test this locally yet which is why I made it a draft PR.

Fix memoize functionality for onApprove callback

---

server/components/buttons/middleware.js

repositioned "Powered by PayPal" as requested
before:
after:

Move 'Powered by PayPal' below card fields container

---

src/api/eligibility.js
src/payment-flows/native.js

This PR adds domain and clientID to the native url. It also adds domain to the nativeEligibility graphql calls.

Add domain and clientID to native url for app switch

---

src/native/popup/popup.js
src/payment-flows/native.js
test/client/nativePopup.js

Still seeing app and web switch in same session due to 500ms timeout not being long enough.  Increasing to ensure web switch only shows in session for customers not having the app.  It took a little over 1s from `#appSwitch` and `pagehide`, therefore, setting the timeout to 1500ms.  This only initiates the Firebase flow, which we don't use, by sending props so will not affect performance.  This will ensure our dashboard is more accurate with regards to top of funnel dropoff.
[FPTI Log:](https://engineering.paypalcorp.com/searchserv-dashboard/fpti-2/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-02-28T05:00:00.000Z',mode:absolute,to:'2021-03-01T04:59:59.999Z'))&_a=(columns:!(transition_name,info_msg,int_error_desc,ext_error_desc,t),filters:!(('$stat …

Fix app switch log

---

src/native/popup/constants.js
src/native/popup/popup.js
src/payment-flows/native.js
test/client/nativePopup.js

This pull request adds handling in the case where we have app switched over to Native for iOS, encountered an issue and fall back to Safari Browser.
**onFallbackListener**
We needed to define another `#` hash listener which will listen to a url containing the `#fallback` fragment. This will then reuse our existing `popupWindow` and redirect to a checkout experience in Safari browser.
```javascript
const onFallbackListener = listen(popupWin, getNativePopupDomain(), POST_MESSAGE.ON_FALLBACK, () => {
getLogger().info(`native_message_onfallback`)
.track({
[FPTI_KEY.TRANSITION]: FPTI_TRANSITION.NATIVE_ON_FALLBACK
}).flush();
fallbackToWebCheckout(popupWin);
});
```
The above is called from `popup.js` where we listen to a redirect.
**popup.js**
```javascript
case HASH.ON_FALLBACK: { …
```

[Native] - iOS Back to Browser

---

src/api/order.js
src/button/validation.js

This PR adds an alternative lookup for the initiation intent passed by merchants that have integrated with the Orders.V2 APIs for an AS2 transaction.

Providing alternative lookup for intent

---

src/api/order.js
src/button/validation.js

PR #105 was recently merged which depends on some back-end changes. There seems to be an issue with those changes so let's revert this to unblock. 
Here's a screenshot of the error folks have been reporting in local development:

Revert "Providing alternative lookup for intent (#105)"

---

src/api/order.js
src/button/validation.js

This PR adds back the alternative lookup for intent and fixes the bug with the graphql query by moving it under cart.
Previous PR: https://github.com/paypal/paypal-smart-payment-buttons/pull/105

Provide alternative lookup for intent v2

---

src/button/exports.js

Adding `intent` to window.props to support pay with nonce flow. It is included as part of `commit` object to meet time constraints

Export intent

---

src/button/exports.js
src/button/pay.js
src/payment-flows/checkout.js
src/payment-flows/types.js

* Pass `userExperienceFlow` through to `updateClientConfig` to support webhooks for pay-with-nonce
* Include `currency` in `exports` to support non-USD merchants in future

Checkout modal fixes

---

.github/workflows/main.yml

This PR removes Node 10 from GitHub workflows, since Node 10 is no longer supported.

Remove Node 10 from GitHub workflows

---

webpack.config.js

This PR fixes the failing CI tests by adding 'web: false' to the webpack config.

Add 'web: false' to webpack config

---

src/props/onAuth.js

Related to https://github.com/paypal/paypal-smart-payment-buttons/pull/115
Problem: Right now, we're not seeing test _**and**_ control logs for the LSAT experiment, only test.
@abarco recommended that we move .logStart() outside of this condition to capture control events too.

fix(LSAT): Moving logStart() to capture test and control

---

server/components/buttons/middleware.js

This PR adds `role="main` to the buttons container `<div>` to resolve an axe-core error being thrown for html landmarks. It also adds an `aria-label` so that the landmarks distinguishable from the parent.

Fix a11y iframe landmark

---

server/service/fundingEligibility.js

This PR removes the query on `flex` for pay later products. We won't be needing this key anymore and won't return it in GraphQL.

Remove flex query from paylater products

---

src/lib/logger.js
src/native/lib/logger.js

- Added new logger event `SDK_ENVIRONMENT` passing the environment where the SDK was executed (ios - android).

Logger event `SDK_ENVIRONMENT`

---

src/payment-flows/native/url.js
test/client/native.js

This PR adds `channel` to the universal link as a generic param for all FI's.
`channel` is being declared and assigned within `getNativeUrlQueryParams`.

Add channel to universal link

---

src/payment-flows/checkout.js
test/client/popup.js

- Modified sequence on the onApprove method to first wait for all promises to get resolved before closing the popup and hiding the checkout overlay.

Hide overlay after onApprove promise(s) get resolved

---

server/service/fundingEligibility.js

This PR updates the pay later product query to include variant and paylater which will be used to brand the pay later button label in specific countries.

Query for variant and paylater

---

src/payment-flows/native/url.js
test/client/native.js

Include buyerCountry code in the URL for universal links. Needed for logging in Android and iOS.

Include buyerCountry code in the URL for universal links

---

src/constants.js
src/native/popup/popup.js
src/payment-flows/native/eligibility.js
src/payment-flows/native/native.js
src/payment-flows/native/popup.js
src/payment-flows/native/socket.js
test/client/mocks.js
test/client/native.js

**Reasoning**
As part of a better onboarding native payment flow will be implementing an opt-out feature that gives the user a choice to use web payment flow instead native. Once a user indicates they do not wish to try native they should fall back to the web flow. In this process, JS SDK will store an opt-out lifetime indicator in localStorage on the device so that SPB no longer app switches to native until the date has expired.
**Implementation**
Now the JS SDK will look for a data type `native_opt_out` on the onFallBack event coming from firebase*. If this type exists and if it is the opt-out type the JS SDK will store the property `nativeOptOutLifetime` on the current `__smart_payment_buttons_storage__` object on the localStorage setting the lifetime to 1 week*.
There is a new method …

Native opt-out fallback

---

server/components/buttons/middleware.js
test/server/render.button.test.js

Currently adding logic in personalization that requires the merchantID. There is no special logic in the graphql layer that requires the sdkMerchatID so this change should be fine.
https://engineering.paypalcorp.com/jira/browse/DTNAVYA-1102

Use merchantID instead of sdkMerchantID for personalization

---

src/payment-flows/checkout.js
test/client/contingency.js

Added new logic to close any previous checkout popup before restarting a new one.
This solves the problem of having two checkouts when there is a rejection and a restart of the checkout flow.
This is now necessary after the modification of the popup closing sequence. (Now the popup only closes after all the promises get resolved on the `onApprove`  method).

Fix restart flow closing previous popup if exists.

---

package.json
server/components/buttons/middleware.js
server/components/buttons/params.js
server/components/native/params.js
server/config/constants.js
server/lib/sdk.js
test/server/render.button.test.js

When the render method for paypal-checkout-components throws an Error, it should be considered an clientErrorResponse and not a serverErrorResponse, thus returning response code 400.

Make button render errors generate clientErrorResponse

---

src/native/popup/popup.js

Currently, if we detect popup in Safari View Controller (SFVC), then we flag this as native ineligible.  We also want to do this for form factors that we don't know (crossover data between Safari and SFVC).

Filter out Unsure SFVC for Native Flow

---

src/native/popup/popup.js
src/payment-flows/native/native.js
src/payment-flows/native/popup.js
src/payment-flows/native/socket.js
test/client/mocks.js

Added logic to receive a prop called `duration` from the native flow opt-out fallback.
- If this prop is passed in and it a valid number representing `milliseconds` it will be used to set the lifetime duration of the native flow opt-out.
- If the duration prop is not passed in, the JS SDK will set a default duration of a `1 week` for the native flow opt-out.

Native flow opt-out duration

---

src/payment-flows/native/native.js

- Actually close the QRCode component on the onClose call per: 
https://engineering.paypalcorp.com/jira/browse/DTCHKINT-925 & https://engineering.paypalcorp.com/jira/browse/DTCHKINT-887
- Wires onCancel callback to use the error UI state per:
https://engineering.paypalcorp.com/jira/browse/DTCHKINT-893
- Removes `setProps` call that was used early on in QA & testing
https://engineering.paypalcorp.com/jira/browse/DTCHKINT-886

QRCode close on  onClose

---

.gitignore
src/native/lib/logger.js
src/payment-flows/applepay/applepay.js
src/payment-flows/applepay/utils.js
src/payment-flows/native/qrcode.js
src/payment-flows/types.js
test/client/native-qrcode.js

* Current QR code logic would let everything through on second eligibility call.  Only want to let `isUserAgentEligible` and `isBrowserMobileAndroid` through.
* Enable Amplitude in popup.

QR Code Logic Fix

---

server/components/buttons/middleware.js
server/service/personalization.jsx

* Calling `merchantIDPromise` promise is not necessary since that parameter is being fetch in the graphl query already:
https://github.paypal.com/Checkout-R/xobuyernodeserv/blob/52923902b33f280bec2585063fbf476e57ef299f/src/graphql/data/Marketing/marketingofferread.js#L427. Therefor the call to `promiseTimeout` is not necessary neither

Remove api call to merchantID when resolving personalization promise

---

src/payment-flows/native/native.js

This fixes a bug where the user clicks Venmo then cancels payment.  Goes back and clicks PayPal but PayPal is ineligible.  The event was erroneously being logged under Venmo FI not PayPal

fix(logging): Move FI tracking from init to onClick

---

src/qrcode/qrcard.jsx

The instruction text
```
To pay, open the Venmo app and scan the QR code above.
```
only makes sense if the QR code is above the instructions.
Replace the instructions with a new text
```
To pay, scan the QR code with your Venmo app
```

Venmo - Update/fix instructions content on Desktop QR code footer

---

src/payment-flows/native/eligibility.js
src/payment-flows/native/native.js
src/payment-flows/native/popup.js

**Reasoning**
After an initial test from the iOS team we found that the opt-out logic wasn't working as expected for the iOS Venice app.
**Changes**
In this PR I'm fixing an issue with the payload data object when passing this payload received from the `fallback` event back to its parent window via `onPostMessage` (postRobot).
I also did a refactor on the existing native opt-out logic.

Fix bug on the iOS opt-out flow.

---

server/components/buttons/params.js

Related to https://github.com/paypal/paypal-checkout-components/pull/1725 and https://github.paypal.com/Checkout-R/clientsdknodeweb/pull/285
In order for the variant based eligibility to carry over it has to be preserved by SPB middleware

Allow for variants to be carried over from initial fundingEligibility

---

src/payment-flows/native/native.js
src/payment-flows/native/popup.js
src/payment-flows/native/qrcode.js
src/qrcode/qrcard.jsx

🚨 Please review the [guidelines for a good PR Description](https://www.pullrequest.com/blog/writing-a-great-pull-request-description/)
Currently the `qrcode` frame does not get cleaned up and there is QRCode specific code in native.js which is a shared location amongst all native flows.  This currently does not impact the customer but want to make this right and tight.
**QR Code**
**QR Escape Path - PayPal**
**QR Escape Path - Guest (Card)**
**QR Escape Path Cleanup of iframe after Checkout**
❤️  Thank you!

Cleanup QRCode Escape Path

---

package.json

Set the dist-tag to alpha when publishing a prelease. 
This is used by grabthar-release when doing `npm publish`: https://github.com/krakenjs/grabthar-release/blob/master/scripts/release.sh#L18
We want to support using `npm run release:pre` for easily publishing prereleases to npm without impacting the latest version.

Set dist tag in pre release script

---

src/qrcode/qrcard.jsx
src/ui/popup.jsx

`closeOnUnload` allows us to set responsibilities on whether the popup is closed if parent is refreshed.  For QR escape paths, we don't want the child to close when the parent closes.
❤️  Thank you!

Use closeOnUnload

---

src/constants.js
src/payment-flows/checkout.js

Track onError calls to determine flow interaction of proposed onError changes:
`onError: (err) => {
// eslint-disable-next-line no-use-before-define
return close().then(() => {
return onError(err);
});
},`

feat: log and track onError checkout calls

---

src/payment-flows/native/eligibility.js
src/payment-flows/native/popup.js

On the iOS fallback the params are always string and for the iOS opt-out it is required to have the `skip_native_duration` as integer.
Added logic on the `setNativeOptOut` to parse to int the `skip_native_duration` on the fallback event.
- https://engineering.paypalcorp.com/jira/browse/DTPPSDK-345
When using the opt-out fallback event and passing `skip_native_duration` (in milliseconds) the JS SDK should handle this properly and set the `nativeOptOutLifetime` calculated as `Date.now()` + `skip_native_duration` (all in milliseconds, unix timestamp).
If the params `skip_native_duration` is not passed on the fallback event the default value should be: `let OPT_OUT_TIME = 6 * 7 * 24 * 60 * 60 * 1000;`

Convert skip native duration from a string to integer

---

src/payment-flows/native/eligibility.js
test/client/native-qrcode.js

Found an issue where native payment flow was being allowed for non-venmo funding sources on desktop.
https://engineering.paypalcorp.com/jira/browse/DTCHKINT-1034
❤️  Thank you!

fix(native payment flow): not eligible if desktop and non-venmo

---

src/native/lib/appDetection.js
src/native/popup/popup.js
src/payment-flows/types.js

Before we returned null if we didn't get anything back for `getInstalledRelatedApps`.  Decision from Android team is to return false to ensure version below are not included.

Fix native app detection

---

src/qrcode/qrcard.jsx

Removing launching the survey on closing the QR code.  Trini asked we keep the survey for future use.
1. Launch QR code
2. Click X button
3. Should not see exit survey
https://engineering.paypalcorp.com/jira/browse/DTCHKINT-1033
❤️  Thank you!

tech(exit survey): Don't show survey on close

---

src/payment-flows/native/qrcode.js
src/qrcode/components.jsx

1. QRCode model should close now with canceled Venmo app payment.
2. Resized the QRCode to be better scannable
1. Launch QRCode
2. Scan with Venmo App
3. Cancel payment in app
Model should close.
https://engineering.paypalcorp.com/jira/browse/DTCHKINT-1026
❤️  Thank you!

fix(qrcode): Close QR model on cancel

---

src/api/fraudnet.js
src/api/order.js

The risk team requires Fraudnet data to be resent when one-click checkout is triggered. We will not need to reload the Fraudnet scripts again, instead, there's a [function](https://engineering.paypalcorp.com/confluence/pages/viewpage.action?spaceKey=RiskDataAcquisition&title=Retrigger+Fraudnet) to call to retrigger and resend Fraudnet data.
https://engineering.paypalcorp.com/jira/browse/DTXOUP-36
1. Alias `paypal-smart-payment-buttons` in `smartcomponentnodeweb`
2. Follow [these steps](https://engineering.paypalcorp.com/confluence/display/CheckoutTOF/LIPP+SPB+Token+Integration) to run the LIPP SPB flow
3. Verify another fraudnet request is sent when the one-click checkout button is clicked
❤️  Thank you!

feat(fraudnet): resend fraudnet data for one click checkout

---

src/payment-flows/native/qrcode.js
src/qrcode/qrcard.jsx
src/types.js

Issue found on customer integration with Blackbaud.  When a payee manually closed the QR window we were not firing the `onCancel` callback to SPB.  This caused an issue with Blackbaud integration and resulted in a bad customer experience.  
1. Visit http://dioceseoftrenton.org/aca-donate-page on Desktop
2. Fill out form at bottom of page
3. Tap "secure payment"
4. Wait for Blackbaud payment page to show Venmo button
5. Click Venmo button
6. Click X to close.  The Blackbaud page will keep spinner because `onCancel` was not called.
❤️  Thank you!

fix(qr modal): onCancel was not being called with model with closed 

---

.github/workflows/main.yml

CI to run on node14 only
We don't need node 12

chore: only run ci on node 14

---

src/lib/dom.test.js

ref: https://github.com/jsdom/jsdom/issues/2924#issuecomment-841831308
thank to @wsbrunson for finding the fix and @elizabethmv for noticing the failures!
We updated to jest 27, via grumbler-scripts v5, which included a new version of JSDOM where this behavior started to fail

Ensure dom tests have elements in body

---

src/api/order.js
src/payment-flows/vault-capture.js

Smart payment buttons throws a generic `Validate payment failed with status: ${ status }` error when `validate-payment-method` call  fails as per [this](https://github.com/paypal/paypal-smart-payment-buttons/blob/master/src/payment-flows/vault-capture.js#L100). Instead we should throw the error message with`issue` code, if available.
Merchants needs to know the exact `issue` code to display the relevant actionable message to the user. 
**Existing**
**Proposed**

set error message based on issue code

---

src/api/order.js
src/card/components/CardName.jsx
src/card/components/fields.jsx
src/card/components/page.jsx
src/card/constants.js
src/card/interface.js
src/card/lib/card-utils.js
src/card/lib/card-utils.test.js
src/card/types.js
src/constants.js
src/menu/page.jsx
test/client/card-fields.js
test/client/mocks.js

Created new preact component and logic for the **optional** Card Holder's Name input for the card fields.
- https://engineering.paypalcorp.com/jira/browse/DTNOR-288
For the card fields we need an optional hosted field for the card holder's name.
The name is not PCI compliance but for the auto-fill browser autofill feature all the card fields related inputs need to be on an iframe for it to work as expected.
This new input can be defined the same way as the `number`, `expiry` and `cvv` the difference is that this input is optional and if is not defined the card fields will be still submit-able.
This new component will only be applicable for the multi card fields meaning that this field won't be able to use in the current implementation for the single card fields. 
This change depends on a …

Card holder name component

---

src/lib/logger.js
src/native/lib/logger.js

Some events logged in Amplitude are not appearing in the right order, this is because we are not sending the key `time` in the properties of each log. We are sending the key `t` however it is got as an extra event property, not as the timestamp of the event. 
Here there is a small experiment made locally using the library [beaver-logger](https://github.com/krakenjs/beaver-logger)
[In the first case](https://analytics.amplitude.com/paypal/project/295320/search/amplitude_id%3D356432994144), logs are sent just like are sent here, without the time key, and they appear disordered... 
[Here is the result](https://analytics.amplitude.com/paypal/project/295320/search/amplitude_id%3D356438516641) when we add the key time
[Jira Ticket](https://engineering.paypalcorp.com/jira/browse/DTCHKINT-1067) …

key time added to fpti logs

---

src/qrcode/qrcard.jsx

Displaying the Venmo escape path only for the default state. This is explained on the jira ticket.
https://venmoinc.atlassian.net/browse/VMORECOMBO-386
1. Press the venmo button on staging/local
2. Press the next state button to see the variations on the QRC 
| Default | Authorize |
| ---- | ---- |
| ![image](https://user-images.githubusercontent.com/89796119/150851824-b30c91aa-c8b5-4654-bd5a-1f1c289ff29b.png) | ![image](https://user-images.githubusercontent.com/89796119/150851879-18e7d392-5bc8-4a48-a6c4-7f95f77a2218.png) |

[QRC Improvements] - Display Venmo escape path only for default state

---

package.json

We no longer need the `npm run release:pre` command, since a new version of **grabthar-release** was cut. Dist-tag and version auto-selection got merged, and `alpha` releases will now be handled via the `npm run release` command: https://github.com/krakenjs/grabthar-release/pull/26

Remove `npm run release:pre`

---

src/button/button.js
src/button/pay.js
src/button/props.js
src/button/props.test.js
src/card/props.js
src/props/createBillingAgreement.js
src/props/createOrder.js
src/props/createSubscription.js
src/props/onApprove.js
src/props/props.js
test/client/data.js
test/client/index.js

This PR updates the callback data to include the selected payment source.
```js
createOrder: function (data, actions) {
return fetch('/your-create-order-url', {
method: 'post',
body: JSON.stringify(
paymentSource: data.paymentSource
)
})
```
This change is required for Venmo vault.
1. Set up local JS SDK with SPB alias
2. Set up createOrder and onApprove callbacks and `console.log(data)` in each
3. Click on a funding source and verify the selected one is available as `paymentSource` in createOrder
4. Complete the transaction and verify the selected one is available as `paymentSource` in onApprove
This change can go out independently.

Pass selected funding to callback data

---

src/lib/session.js

Support for https://engineering.paypalcorp.com/jira/browse/DTALTPAY-854
Buyers who wait 20+ minutes to click on payment button are losing the __session__.state object required to continue through unbranded flow. The default lifetime for belter session (saved in localStorage) is 20 minutes. This change leaves belter default untouched and extends the expiration to 60 minutes through the `lifetime` param of the `getStorage()` function.
The goal of extending the expiration is to reduce the occurrence of the buyer being redirected to branded flow.
- Use drop-in UI (alternative payments unbranded SDK) integration. Enter buyer information.
- Observe localStorage `__session__` contents (check Application tab in dev tools or `window.localStorage.__paypal_storage__` in console).
- Leave window …

fix: extend session lifetime to reduce occurrence of branded flow redirect

---

.github/pull_request_template.md

Adds a section to tag groups or individuals to review the PR. 
Codeowners (checkout-sdk) are only able to request reviews on PRs, meaning that cross-team internal contributors cannot use this feature. As an alternative, we've added a section to tag them for review in the PR description.
N/A
N/A

Update PR template with review section

---

src/payment-flows/card-form.js

Prevents Inline XO experience if cross-site tracking is enabled.

Inline XO: Cross-site tracking

---

src/api/order.js
src/payment-flows/vault-capture.js
test/client/mocks.js
test/client/vault.js

Currently, when using the vault-capture flow, after we apply the payment (by calling the `validate-payment-method` endpoint), we have not actually approved the order. For some of our merchants, they validate that the order is approved before they will attempt to capture the order.
This PR adds in an additional call to the Orders API to `confirm-payment-method` that will set the order to `APPROVED` based on the user action
PPPLMER-104024
* Visit https://www.te-cibns.qa.paypal.com/xo-integrations/vaulting/client-token
* Set a breakpoint in the `onApprove` method prior to calling capture on the order
* Populate the customer_id of `test-1654613061212`
* Upon Setting the customer ID and waiting for the buttons to re-render, you should see the one-click buttons
* Click the one-click button
* …

Fix for approving an order during the vault capture flow

---

src/button/button.js
src/button/pay.js
src/payment-flows/card-form.js
src/payment-flows/checkout.js
src/props/onComplete.js
src/props/props.js
test/client/inlinexo.js

Adds `capture` and `get` to actions for `onComplete` callback and also `intent` to the data attribute.  This allows merchants to capture the order if `intent=authorize` and authorization is done in the app.

Update onComplete data and actions

---

server/components/buttons/middleware.js

Fixed an issue with a log payload that didn't send the correct information
https://engineering.paypalcorp.com/jira/browse/DTLITEPLAT-546
1. Render the button in any environment
2. Check that the cpl_comp_metrics field is send correctly
❤️  Thank you!

Fixed issue with log payload for latency instrumentation

---

src/card/components/CardCVV.jsx
src/card/components/CardExpiry.jsx
src/card/components/CardName.jsx
src/card/components/CardNumber.jsx
src/card/components/CardPostalCode.jsx
src/card/components/fields.jsx
src/card/components/page.jsx
src/card/constants.js
src/card/lib/card-checks.js
src/card/lib/card-checks.test.js
src/card/lib/card-focus.test.js
src/card/lib/card-utils.js
src/card/lib/card-utils.test.js
src/card/lib/methods.js
src/card/types.js

Multi Card Fields pulls in the `card-validator` module, but only used it to verify the expiry date. This refactors how validations are done for the CardName, CardNumber, CardCVV, and CardPostalCode fields to use this module. This also adds communication between the CardNumber field and the CardCVV field, so as the card number changes the security code placeholder and max length will update based on the determined card type.
- [DTNOR-558](https://engineering.paypalcorp.com/jira/browse/DTNOR-558)
Screenshots showing the CVV placeholder text changing depending on the card type:
Co-Authored By:
- @bywood
- @jplukarski
- @nidhinarendra
❤️  Thank you!

Refactoring of multi-card field validation

---

src/payment-flows/vault-capture.js

When calling the `confirm-payment-source` endpoint we previously used the facilitator access token. This works for most use cases, but for partner scenarios (CP4 in particular) it can cause the `confirm-payment-source` request to fail. 
This build has been verified by the PPCP team using CP3, CP4, and other integrations.
PPPLMER-113816
Pass in client-token generated using a CP4 scenario with a vaulted user account. When clicking on the one-click button in the returning buyer scenario, you should see a request to `v2/orders/confirm-payment-source`. This previously would fail but should now succeed.
❤️  Thank you!

Update vault flow to use client token instead of merchant token

---

src/payment-flows/payment-fields.js

Initial inline payment fields PR - https://github.com/paypal/paypal-smart-payment-buttons/pull/473
Observed below UX improvements after the initial release, and fixed all those in this PR.
- disable the extra fields rendering on clicking the SPB
- improve the rendering experience of APM button while showing the fields (avoid reloading of APM button once clicked)
------------------
BEFORE:
---------------------------------------------------
**AFTER:**
❤️  Thank you!

Inline payment fields UX improvements

---

src/api/fraudnet.js

This PR leverages the new xprops `buttonLocation` that was introduced in https://github.com/paypal/paypal-checkout-components/pull/2028
We are making this change so that the fraudnet team can better detect fraudulent purchases depending on the domain that loaded the SDK.
https://engineering.paypalcorp.com/jira/browse/DTCHKINT-1214
See screenshots section (help wanted 👋 )
I am unable to test this locally.
I can see the compiled code is present: 
but the new prop is absent: 
I tried running the standard integration that points to local csnw that loads scnw 
❤️  Thank you!

send xprops.buttonLocation value to fraudnetConfig

---

src/api/order.js
src/card/components/CardCVV.jsx
src/card/components/CardExpiry.jsx
src/card/components/CardName.jsx
src/card/components/CardNumber.jsx
src/card/components/CardPostalCode.jsx
src/card/components/fields.jsx
src/card/components/page.jsx
src/card/interface.js
src/card/lib/card-checks.js
src/card/lib/card-checks.test.js
src/card/lib/card-utils.js
src/card/lib/card-utils.test.js
src/card/lib/exports.js
src/card/props.js
src/card/types.js

This adds the getState method to the unbranded multi-card fields. This method returns a state object to the merchant with the following information:
- code
- type
- niceType
- isFocused
- isEmpty
- isPotentiallyValid
- isValid
[DTNOR-487](https://engineering.paypalcorp.com/jira/browse/DTNOR-487)
https://github.com/paypal/paypal-checkout-components/pull/2033
https://github.com/orgs/paypal/teams/checkout-sdk
❤️  Thank you!
@jplukarski 
@nidhinarendra
@siddy2181

feat(getState()): add getState Method to Unbranded Multi-Card Fields 

---

src/card/lib/index.js
src/card/lib/index.test.js

Refactored `cardExpiryToPaymentSourceExpiry(dateString)` function to return the expected month when the card expiry date is in December. Added unit tests for this function.
Submit HCFs with a December card expiry date (12/2023, 12/23, etc.)
The order will be submitted with the wrong date.
❤️  Thank you!

Fixed bug where cardExpiryToPaymentSourceExpiry returns the wrong date

---

src/button/logger.js
src/card/constants.js
src/card/interface/getCardFields.js
src/card/lib/card-utils.js
src/card/lib/card-utils.test.js

Preventing `submitCardFields()` to complete if the cardholder name is invalid. This change is for all optional fields. The expected behaviour is to prevent any API calls to happen if we know there's a mistake on the forms, and log them for the merchant.
https://paypal.atlassian.net/browse/DTCURIOSTY-8477
https://paypal.atlassian.net/browse/DTNOR-863
Render the cardholderName field, and fill it out using only digits. The payment should not be going through, but it's currently ignoring this field as it's an optional field. This fix will prevent the flow from continuing.
❤️  Thank you!

preventing onSubmit if cardholder name is invalid

---

src/api/vault.js
src/card/interface/submitCardFields.js
src/card/interface/submitCardFields.test.js
src/card/interface/vault-without-purchase.js
src/card/interface/vault-without-purchase.test.js

`GET /v3/vault/setup-tokens/:id` needs special permission to call, and we don't need to use it on the sdk anyway. We can just use `update` and check contingencies that happen from the update call
EDIT:
We are also adding back the passing of the id token to the graphql update token endpoint.
We don't think its required for the vault without purchase flow but we still need to pass it until we can deploy xobuyernodeserv with a fix to make it optional.

remove unneeded get setup token call

---

src/card/constants.js

Occasionally, when the `cardType` returns to its default state, the card CVV is being marked as invalid because it's length isn't matching the one on the input.
Intermittent, not always reproducible but happens frequently when the buyer modifies a valid card number after the CVV is filled out.
❤️  Thank you!

bug: cvv being marked as invalid when cardType defaults

---

src/api/order.js
src/button/button.js
src/button/props.js
src/button/props.test.js
src/props/legacyProps.js
src/props/legacyProps.test.js
src/props/onShippingChange.js
src/props/onShippingChange.test.js
src/types.js

See #525 for history. 
Use a newly passed Elmo experiment to conditionally use the UpdateShipping mutation in the onShippingChange callback function. 
https://paypal.atlassian.net/browse/DTOPPOR-1189
Uses a new Elmo experiment to conditionally use the UpdateShipping mutation, rather than Patch Order REST call, when the onShippingChange callback is called.
Elmo: https://internal.msmaster.qa.paypal.com/elmo/experiment/125252
smartcomponents PR: https://paypal.atlassian.net/browse/DTOPPOR-1189
❤️  Thank you!

Conditionally use UpdateShipping mutation in onShippingChange

---

src/card/components/fields.jsx
src/card/interface/getCardFields.js
src/card/interface/submitCardFields.js
src/card/lib/card-checks.js
src/card/lib/card-checks.test.js

When the merchant account is ineligible for certain card types(Discover,Amex),the form is able to submit successfully even though the field is marked as invalid.
The orders API team confirmed that the payment would decline on their end after the call is made.
We'll no longer mark ineligible cards as invalid and will allow the call to orders API to go through. The response will be an error and we can surface this to the merchant so they can decide and handle what to do on their site when a buyer attempts to make a purchase with an ineligible card type.
Additionally, when we detect that a card is ineligible for either the purchase or vaulting flow, we'll throw an error for the merchant to know and handle any UI changes on their end.
https://paypal.atlassian.net/browse/DTCURIOSTY-8609
Type …

chore: no longer marking ineligible cards as invalid

---

src/card/components/page.jsx

Currently, the stateObject returned during the `onChange` inputEvent has one of the fields as `isFieldPotentiallyValid` as opposed to `isPotentiallyValid`. This PR is to fix that bug.
❤️  Thank you!

fix: update fieldName to isPotentiallyValid

---

src/button/pay.js
src/types.js

This new `isButtonClientConfigCallBlocking` feature flag controls the update client config mutation blocking behavior for the Buttons component. By default, this call is non-blocking. When this feature flag is true, this call will be blocking and will pause the popup flow until its complete.

Add feature flag to control button config mutation behavior

---

src/button/logger.js
src/button/logger.test.js

* Added warning log when SDK version used for first render doesn't match SDK version used for server-side render.
To increase visibility of fallback rendering behaviors in SCNW
❤️  Thank you!

chore: add log for render version mismatch

---

src/lib/register-service-worker.js

We currently use the BroadcastChannel browser API in the App Shell service worker. However, we do not currently have checks for browser support of this API, so we add that check prior to service worker registration.
DTLITEPLAT-1147
Run the App Shell flow locally (internal documentation). Test on browser versions that support and don't support BroadcastChannel. Ensure that the service worker only gets registered when the browser version supports service workers and BroadcastChannel.
[https://caniuse.com/broadcastchannel](https://caniuse.com/broadcastchannel)
[https://caniuse.com/serviceworkers](https://caniuse.com/serviceworkers)
❤️  Thank you!

add browser eligiblity check for app shell service worker registration

---

src/props/onShippingChange.js
src/props/onShippingChange.test.js

- Update regex sanitization pattern for `patchShipping` mutation to allow changing the shipping name.
- We discovered that `checkoutsellerplatserv` allows patching the shipping name with a low access token; hence, we're modifying the sanitization rules to allow it. 
- Update regex sanitization pattern for `patchShipping` mutation to allow changing the shipping name.
- We discovered that `checkoutsellerplatserv` allows patching the shipping name with a low access token; hence, we're modifying the sanitization rules to allow it.
❤️  Thank you!

(feat): Update sanitization rules for patchShipping

---

src/api/payment.js

This adds a new optional param in the Approve Applepay graphql mutation in order to specify that the applepay flow is coming from Smart Payment Buttons rather than the applepay custom component.
ApplePay flow can come from more than one integration. On the SDK we have SPB and Custom Components.
https://paypal.atlassian.net/browse/DTALTPAY-1623
Integration with applepay enabled will include applepay SPB. Selecting the applepay payment method will start the flow. Buyer approval leads to the approve applepay payment mutation call.
Alternately, specifying `components=applepay` uses the `paypal-applepay-components` custom component. 
Changes to xobuyer mutation are for an optional variable, so this is a non-breaking change.
❤️  Thank you!

feat: send product flow to approve payment mutation

---

src/card/constants.js

.card-icon class was modified to support custom padding in style prop for paypal.CardFields. Previously we had a hard-coded amount of space from the top, so when users passed custom padding that amount would still be fixed and would cause an overflow of the icon. The proposed solution is to make the icon be centered regardless of padding or line-height etc.. An _!important_ was also added to the .card-field-number.display-icon class in order for it to take precedence over custom padding so that the card number always remains to the right of the card icon.
Issue was brought up by a merchant that observed that the payment card icon would overflow whenever a custom padding was passed into paypal.CardFields({style:{}}).
❤️  Thank you!

Fix custom padding overflow issue with payment card icon

---

src/props/onApprove.js
src/props/onApprove.test.js
src/props/onShippingChange.js
src/props/onShippingChange.test.js
src/types.js

Remove unused elmo experiment btSdkOrdersV2Migration
[DTPPCPSDK-1271](https://paypal.atlassian.net/browse/DTPPCPSDK-1271)
Experiment will also need to be removed from [smartcomponentnodeweb](https://github.paypal.com/Checkout-R/smartcomponentnodeweb)
❤️ Thank you!

Remove btSdkOrdersV2Migration experiment
